---
title: "clustering"
author: "Pablo Suarez"
date: "2024-04-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
### load library
library(factoextra)
library(NbClust)
library(tidyverse)
#Necessary for date parsing.
library(lubridate)
#Necessary for column name cleaning.
library(janitor)
#Eventually necessary for visualization
library(ggthemes)
#Necessary for Census API calls.
library(tidycensus)
#Eventually necessary for visualizations.
library(ggplot2)
#Potentially necessary for cleaning.
library(ggrepel)
#Eventually necessary for visualizations.
library(tigris)
#Simple features.
library(sf)
```

```{r}

pg_foreclosures_per_tract <- read_csv("pg_foreclosures_per_tract.csv")
View(pg_foreclosures_per_tract)

```

1. Hierarchical Clustering Method

```{r}
### lets dive into hierarchial clustering now
library(cluster)
# Dissimilarity matrix
d <- dist(pg_foreclosures_per_tract, method = "euclidean")

# Hierarchical clustering using Complete Linkage
hc1 <- hclust(d, method = "complete" )

# Plot the obtained dendrogram
plot(hc1, cex = 0.6, hang = -1)

```


```{r}
h_df = pg_foreclosures_per_tract 
# Step 1: Perform hierarchical clustering
hc <- hclust(dist(h_df))

# Step 2: Plot the dendrogram
plot(hc)

# Step 3: Cut the dendrogram to obtain cluster assignments
num_clusters <- 8  # Change this to the desired number of clusters
cluster_assignments <- cutree(hc, k = num_clusters)

# Step 4: Associate variable names with cluster assignments
h_df$cluster <- cluster_assignments

```


```{r}

h_df |>
  group_by(cluster) |>
  summarise_all(mean)

```


Variables of note: tract_medincome_2020, tract_medincome_2010, post_2010_foreclosures, ownoccupied_2020



```{r}

clusterGroups = cutree(hc1, k = 8)

table(clusterGroups)

```


```{r}

plot(x = clusterGroups, y = h_df$tract_number)

```


2. Partitional Clustering Method (kmeans)

```{r}


p_df <- scale(pg_foreclosures_per_tract)

# kmeans with 2 clusters
set.seed(150)
k2 <- kmeans(p_df, centers = 2)
str(k2)

# visualize cluster assignment
fviz_cluster(k2, data = df)

# 100 random initialization 
k2 <- kmeans(p_df, centers = 2, nstart= 100)
str(k2)
fviz_cluster(k2, data = p_df)

# Elbow method
fviz_nbclust(p_df, kmeans, method = "wss")

k2 <- kmeans(p_df, centers = 3, nstart= 100)

# did the tot.withinss (sum of squared error) improve?
str(k2)
fviz_cluster(k2, data = p_df)

```


3. Spectral Clustering Method


We used k means and selected k to be 3 after testing 2-5 values. 

```{r}

s_df <- pg_foreclosures_per_tract

set.seed(123)
k=3
km.out <- kmeans(s_df, centers = k, nstart = 20)
s_df$Cluster <- factor(km.out$cluster)

ggplot(s_df, aes(Cluster, tract_number, color = Cluster)) +
    geom_point(alpha = 0.25) 

```


```{r}

ggplot(s_df, aes(tract_medincome_2020, tract_medincome_2010, color = Cluster)) +
    geom_point(alpha = 0.25) 

```

```{r}

ggplot(s_df, aes(post_2010_foreclosures, tract_medincome_2010, color = Cluster)) +
    geom_point(alpha = 0.25) 

```

```{r}

ggplot(s_df, aes(foreclosure_pc_2010, tract_medage_2020, color = Cluster)) +
    geom_point(alpha = 0.25) 

```

